services:
  library:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    container_name: library
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ..:/app
      - ~/.m2:/root/.m2
    environment:
      - MAVEN_OPTS=-Xmx1024m
